/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsla.tests

import axcore.ModelA
import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(MyDslAInjectorProvider)
class MyDslAParsingTest {
	@Inject
	ParseHelper<ModelA> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			a1 test
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
