/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydslb.tests

import bxcore.ModelB
import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(MyDslBInjectorProvider)
class MyDslBParsingTest {
	@Inject
	ParseHelper<ModelB> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			b1 test
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
